// Created by iWeb 2.0.4 local-build-20100521

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,262),url:'Welcome__files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Welcome__files/stroke_1.png'},{rect:new IWRect(1,-1,148,2),url:'Welcome__files/stroke_2.png'},{rect:new IWRect(149,-1,2,2),url:'Welcome__files/stroke_3.png'},{rect:new IWRect(149,1,2,262),url:'Welcome__files/stroke_4.png'},{rect:new IWRect(149,263,2,2),url:'Welcome__files/stroke_5.png'},{rect:new IWRect(1,263,148,2),url:'Welcome__files/stroke_6.png'},{rect:new IWRect(-1,263,2,2),url:'Welcome__files/stroke_7.png'}],new IWSize(150,264)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,263),url:'Welcome__files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Welcome__files/stroke_9.png'},{rect:new IWRect(1,-1,287,2),url:'Welcome__files/stroke_10.png'},{rect:new IWRect(288,-1,2,2),url:'Welcome__files/stroke_11.png'},{rect:new IWRect(288,1,2,263),url:'Welcome__files/stroke_12.png'},{rect:new IWRect(288,264,2,2),url:'Welcome__files/stroke_13.png'},{rect:new IWRect(1,264,287,2),url:'Welcome__files/stroke_14.png'},{rect:new IWRect(-1,264,2,2),url:'Welcome__files/stroke_15.png'}],new IWSize(289,265))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Welcome__files/Welcome_Moz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');fixAllIEPNGs('Media/transparent.gif');fixupAllIEPNGBGs();applyEffects()}
